services:
  musicstore:
    build:
      context: ./MusicStore
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sqlserver 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - music-network
    restart: on-failure

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "Password626!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
     - sqlvolume:/var/opt/mssql
    networks:
      - music-network

networks:
  music-network:

volumes:
   sqlvolume:
